### ISSUE TITLE
Schriftkontrast

### ISSUE THREAD

**Issue by the-zimmermann** [YannicKraegenbrink/exam#2]
Der Kontrastwert auf den Boxen ist sehr gering:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/75070374/188569997-bc0c8773-ffe2-491d-aab6-f3fcce29cbea.png">

Um so höher die Helligkeit des Bildschirms, umso schwieriger wird es zu lesen sein. Hier würde sich fast anbieten, schwarz zu nehmen.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/75070374/188570217-7fb023b1-fae6-4e8b-acb1-ab9f693b8aae.png">

Ich würde jedoch eher den Hintergrund abdunkeln, weil der Kontrast zum Hintergrund und das Wiederholen dessen ganz gelungen ist.

Das gleiche gilt für den Gradient generell.

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/75070374/188570545-00f37a89-5bef-4350-b939-8a68da63861d.png">

Damit du dich nicht immer wiederholst, kannst du auch [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) nutzen.

Einfach oben:

```css
:root {
  --background-gradient: linear-gradient(45deg, #30b79f 0%, #5061ab 100%);
}
```

Nutzung dann einfach so:
```css
#button {
  ...
  background-image: var(--background-gradient);
  ...
}
```

Habe mit dem Beispiel gleich mal die Farben abgedunkelt:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/75070374/188571690-8b5b29ee-10b8-499b-9c36-121a877b9989.png">

Kannst du aber gern mit spielen.
